---
title: "2007 NOAA National Climatic Data Center Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(p8105.datasets)
library(plotly)

data("ny_noaa")

## Changed units, restricted data to 2007 only

ny_noaa = 
  ny_noaa %>% 
  separate(date, into = c("year", "month", "day"), sep = "-") %>% 
  mutate(
    month = month.name[as.numeric(month)],
    tmax = as.numeric(tmax), 
         tmin = as.numeric(tmin) / 10,
         tmax = tmax / 10,
         prcp = prcp / 10) %>% 
  filter(year == 2007)
```

Column {data-width=650}
-----------------------------------------------------------------------

### Scatterplot of snowfall against maximum temperature for days with reported snowfall

```{r}
ny_noaa %>% 
  mutate(
month = factor(month, levels = month.name, ordered = TRUE)
) %>% 
  filter(snow !=0) %>% 
  plot_ly(
    x = ~tmax,
    y = ~snow,
    type = "scatter", mode = "markers",
    alpha = 0.4,
    color = ~month
  )
```

Column {data-width=350}
-----------------------------------------------------------------------

### Chart B

```{r}

```

### Chart C

```{r}

```

