---
title: "Resume"
---

*Click [here](Amy Yeung Resume.pdf) for my full resume as a PDF.*

# Education

### Columbia University Mailman School of Public Health (May 2023)
*New York, NY*

**Master of Public Health in Epidemiology (MPH)**

* GPA: 4.1
* Certificate in Applied Biostatistics & Public Health Data Science
* Leadership: Bloom Mentoring (2022), Healthcare Data Analytics (2022), Mailman Consulting Club (2022) 
* Relevant Coursework: Machine Learning, Data Science, Applied Regression, Health Accounting & Budgeting

### The University of Hong Kong (May 2021)
*Hong Kong*

**Bachelor of Biomedical Sciences (BBiomedSc)**

* GPA: 3.7 (First Class Honours)
* Awards: Dean’s Honours List (2020-2021), APRU Global Health Virtual Case Competition (2019, 2021) 
* Leadership: AIESEC in HKU (2017-2019), Biomedical Sciences Society (2017-2018)

### University of California at Berkeley (May 2020)
*Berkeley, CA*

**Study Abroad**

* GPA: 3.9
* Exchange year, took graduate-level public health classes


# Experience

### Columbia University Mailman School of Public Health (Summer 2022)
*New York, NY*

**Research Assistant**

* Conducted literature research using Pubmed and Law Atlas and co-wrote the significance section of 3 grant proposals on substance use and health policies to obtain funding for separate research projects
* Spearheaded a self-conceived independent research topic investigating complex survey data from the National Survey of Drug Use and Health with R and SAS

### The University of Hong Kong School of Public Health 
*Hong Kong*

**Student Research Assistant (Summer 2021)**

* Wrangled Hong Kong COVID-19 case data from the Centre for Health Protection with Excel to infer 1,800 transmission pairs from over 5,000 cases which were used as a preface for 3 in-depth research projects
* Accurately communicated findings by co-authoring 3 manuscripts for publication in epidemiological journals and creating figures for visualization after analysis with R. Received 37 citations and ≥ 5,000 views

**Student Research Assistant (Summer 2020)**

* Generated search algorithm on Pubmed, collected and analyzed data from over 400 articles with Excel and R, created visuals figures and reported findings by writing a published journal article. Received 12 citations and 1,600 views

### Being Patient
*Virtual*

**Summer Intern**

* Designed a curriculum for a proposed online course on dementia for the 40,000 members and created modules with content and visuals from research articles using precise and concise language with Keynote
* Authored an article on the platform by reporting findings from a scientific journal in a simplified manner, receiving the most engagement on the platform since 2020

# Leadership

### Bloom Mentoring (Jan 2022 - Present)
*New York, NY*

**Vice President, Columbia University Mailman School of Public Health Chapter**

* Successfully implemented 3 campus events in compliance with university rules by organizing meetings and unifying ideas from board members. Increased membership by 83%, increased social media engagement by 300% 
* Partnered with other school organizations and external stakeholders to organize a collaborative event series focused on promoting menstrual equity to students

### AIESEC in HKU (June 2018 - May 2019)
*Hong Kong*

**Manager of Talent Management, The University of Hong Kong Chapter**

* Organized 4 recruitment talks, led the interview and selection process from over 200 candidates to over 30 members, and facilitated an induction camp to introduce members to organizational and chapter goals
* Supervised my team of 6 members to facilitate monthly events and coaching sessions to boost organizational knowledge, raise social awareness and empower members in alignment with the targets set by the Vice President

# Skills and Languages

**Skills:** R, Python, SAS, SQL, STATA, Microsoft Office (Excel, PowerPoint, Word), Git, Final Cut Pro

**Languages:** English (Native), Cantonese (Fluent) Mandarin (Fluent), Spanish (Intermediate)


